import { createFileRoute } from "@tanstack/react-router";
import {
  AlertCircle,
  AlertTriangle,
  ShieldAlert,
  HeartPulse,
  Brain,
  Briefcase,
  GraduationCap,
  Coins,
} from "lucide-react";
import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/_app/interventions")({
  head: () => ({ meta: [{ title: "Risk Dashboard · Sahaayak AI" }] }),
  component: Interventions,
});

function Interventions() {
  const [interventions, setInterventions] = useState<any[]>([]);

  useEffect(() => {
    setInterventions([
      {
        id: "int1",
        type: "FINANCIAL",
        severity: "HIGH",
        reason: "Missed AICTE Pragati Scholarship deadline by 2 days.",
        recommended_action:
          "Schedule a session with a financial aid mentor to find alternatives.",
        status: "PENDING",
      },
      {
        id: "int2",
        type: "ENGAGEMENT",
        severity: "MEDIUM",
        reason: "No logins detected for 15 consecutive days.",
        recommended_action:
          "Send automated 'Welcome Back' email with a quick survey.",
        status: "PENDING",
      },
      {
        id: "int3",
        type: "CAREER",
        severity: "LOW",
        reason: "System Design module taking 3x longer than average.",
        recommended_action:
          "Recommend supplementary YouTube playlist for System Design.",
        status: "RESOLVED",
      },
    ]);
  }, []);

  return (
    <div className="space-y-4">
      <header className="glass-strong shadow-soft relative overflow-hidden rounded-3xl p-6 md:p-8 bg-gradient-to-br from-destructive/10 to-transparent">
        <div className="flex items-center gap-4">
          <div className="grid size-14 place-items-center rounded-2xl bg-destructive/20 text-destructive">
            <ShieldAlert className="size-7" />
          </div>
          <div>
            <h1 className="text-2xl font-bold tracking-tight md:text-3xl">
              Intervention Dashboard
            </h1>
            <p className="text-sm text-muted-foreground">
              Proactive risk alerts generated by the No Student Left Behind
              Engine.
            </p>
          </div>
        </div>
      </header>

      <div className="space-y-4">
        {interventions.map((int, idx) => (
          <InterventionCard key={idx} intervention={int} />
        ))}
      </div>
    </div>
  );
}

function InterventionCard({ intervention }: { intervention: any }) {
  const { type, severity, reason, recommended_action, status } = intervention;

  const getIcon = () => {
    switch (type) {
      case "FINANCIAL":
        return <Coins className="size-5" />;
      case "ACADEMIC":
        return <GraduationCap className="size-5" />;
      case "CAREER":
        return <Briefcase className="size-5" />;
      case "MENTAL_WELLNESS":
        return <HeartPulse className="size-5" />;
      case "ENGAGEMENT":
        return <Brain className="size-5" />;
      default:
        return <AlertCircle className="size-5" />;
    }
  };

  const getSeverityColor = () => {
    switch (severity) {
      case "HIGH":
        return "text-destructive bg-destructive/10 border-destructive/20";
      case "MEDIUM":
        return "text-warning bg-warning/10 border-warning/20";
      case "LOW":
        return "text-primary bg-primary/10 border-primary/20";
      default:
        return "text-muted-foreground bg-muted border-border";
    }
  };

  const isResolved = status === "RESOLVED";

  return (
    <div
      className={`glass rounded-2xl p-4 border flex flex-col md:flex-row gap-4 md:items-center justify-between ${isResolved ? "opacity-50 grayscale" : ""}`}
    >
      <div className="flex items-start gap-4">
        <div
          className={`size-10 rounded-xl grid place-items-center shrink-0 border ${getSeverityColor()}`}
        >
          {getIcon()}
        </div>
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span
              className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase ${getSeverityColor()}`}
            >
              {severity} RISK
            </span>
            <span className="text-xs font-semibold text-muted-foreground">
              {type}
            </span>
          </div>
          <p className="font-medium text-sm text-foreground/90">{reason}</p>
          <p className="text-xs text-muted-foreground mt-1">
            <b>Action:</b> {recommended_action}
          </p>
        </div>
      </div>
      {!isResolved && (
        <div className="flex gap-2">
          <Button variant="outline" size="sm" className="rounded-full">
            Dismiss
          </Button>
          <Button
            size="sm"
            className="rounded-full bg-primary/10 text-primary hover:bg-primary/20"
          >
            Execute Action
          </Button>
        </div>
      )}
    </div>
  );
}
