/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVoiceRouteImport } from './routes/_app.voice'
import { Route as AppSuccessStoriesRouteImport } from './routes/_app.success-stories'
import { Route as AppSuccessNavigatorRouteImport } from './routes/_app.success-navigator'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScholarshipsRouteImport } from './routes/_app.scholarships'
import { Route as AppSchemesRouteImport } from './routes/_app.schemes'
import { Route as AppResumeRouteImport } from './routes/_app.resume'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPredictionsRouteImport } from './routes/_app.predictions'
import { Route as AppParentRouteImport } from './routes/_app.parent'
import { Route as AppOpportunitiesRouteImport } from './routes/_app.opportunities'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMentorsRouteImport } from './routes/_app.mentors'
import { Route as AppKnowledgeGraphRouteImport } from './routes/_app.knowledge-graph'
import { Route as AppInterventionsRouteImport } from './routes/_app.interventions'
import { Route as AppDigitalTwinRouteImport } from './routes/_app.digital-twin'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCommunityRouteImport } from './routes/_app.community'
import { Route as AppCareerGpsRouteImport } from './routes/_app.career-gps'
import { Route as AppApplicationsRouteImport } from './routes/_app.applications'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAiMentorRouteImport } from './routes/_app.ai-mentor'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppSuccessStoriesRoute = AppSuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => AppRoute,
} as any)
const AppSuccessNavigatorRoute = AppSuccessNavigatorRouteImport.update({
  id: '/success-navigator',
  path: '/success-navigator',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScholarshipsRoute = AppScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => AppRoute,
} as any)
const AppSchemesRoute = AppSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionsRoute = AppPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AppRoute,
} as any)
const AppParentRoute = AppParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorsRoute = AppMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeGraphRoute = AppKnowledgeGraphRouteImport.update({
  id: '/knowledge-graph',
  path: '/knowledge-graph',
  getParentRoute: () => AppRoute,
} as any)
const AppInterventionsRoute = AppInterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => AppRoute,
} as any)
const AppDigitalTwinRoute = AppDigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerGpsRoute = AppCareerGpsRouteImport.update({
  id: '/career-gps',
  path: '/career-gps',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiMentorRoute = AppAiMentorRouteImport.update({
  id: '/ai-mentor',
  path: '/ai-mentor',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin': typeof AppAdminRoute
  '/ai-mentor': typeof AppAiMentorRoute
  '/analytics': typeof AppAnalyticsRoute
  '/applications': typeof AppApplicationsRoute
  '/career-gps': typeof AppCareerGpsRoute
  '/community': typeof AppCommunityRoute
  '/dashboard': typeof AppDashboardRoute
  '/digital-twin': typeof AppDigitalTwinRoute
  '/interventions': typeof AppInterventionsRoute
  '/knowledge-graph': typeof AppKnowledgeGraphRoute
  '/mentors': typeof AppMentorsRoute
  '/notifications': typeof AppNotificationsRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/parent': typeof AppParentRoute
  '/predictions': typeof AppPredictionsRoute
  '/profile': typeof AppProfileRoute
  '/resume': typeof AppResumeRoute
  '/schemes': typeof AppSchemesRoute
  '/scholarships': typeof AppScholarshipsRoute
  '/settings': typeof AppSettingsRoute
  '/success-navigator': typeof AppSuccessNavigatorRoute
  '/success-stories': typeof AppSuccessStoriesRoute
  '/voice': typeof AppVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin': typeof AppAdminRoute
  '/ai-mentor': typeof AppAiMentorRoute
  '/analytics': typeof AppAnalyticsRoute
  '/applications': typeof AppApplicationsRoute
  '/career-gps': typeof AppCareerGpsRoute
  '/community': typeof AppCommunityRoute
  '/dashboard': typeof AppDashboardRoute
  '/digital-twin': typeof AppDigitalTwinRoute
  '/interventions': typeof AppInterventionsRoute
  '/knowledge-graph': typeof AppKnowledgeGraphRoute
  '/mentors': typeof AppMentorsRoute
  '/notifications': typeof AppNotificationsRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/parent': typeof AppParentRoute
  '/predictions': typeof AppPredictionsRoute
  '/profile': typeof AppProfileRoute
  '/resume': typeof AppResumeRoute
  '/schemes': typeof AppSchemesRoute
  '/scholarships': typeof AppScholarshipsRoute
  '/settings': typeof AppSettingsRoute
  '/success-navigator': typeof AppSuccessNavigatorRoute
  '/success-stories': typeof AppSuccessStoriesRoute
  '/voice': typeof AppVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai-mentor': typeof AppAiMentorRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/career-gps': typeof AppCareerGpsRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/digital-twin': typeof AppDigitalTwinRoute
  '/_app/interventions': typeof AppInterventionsRoute
  '/_app/knowledge-graph': typeof AppKnowledgeGraphRoute
  '/_app/mentors': typeof AppMentorsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/opportunities': typeof AppOpportunitiesRoute
  '/_app/parent': typeof AppParentRoute
  '/_app/predictions': typeof AppPredictionsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/resume': typeof AppResumeRoute
  '/_app/schemes': typeof AppSchemesRoute
  '/_app/scholarships': typeof AppScholarshipsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/success-navigator': typeof AppSuccessNavigatorRoute
  '/_app/success-stories': typeof AppSuccessStoriesRoute
  '/_app/voice': typeof AppVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/ai-mentor'
    | '/analytics'
    | '/applications'
    | '/career-gps'
    | '/community'
    | '/dashboard'
    | '/digital-twin'
    | '/interventions'
    | '/knowledge-graph'
    | '/mentors'
    | '/notifications'
    | '/opportunities'
    | '/parent'
    | '/predictions'
    | '/profile'
    | '/resume'
    | '/schemes'
    | '/scholarships'
    | '/settings'
    | '/success-navigator'
    | '/success-stories'
    | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/ai-mentor'
    | '/analytics'
    | '/applications'
    | '/career-gps'
    | '/community'
    | '/dashboard'
    | '/digital-twin'
    | '/interventions'
    | '/knowledge-graph'
    | '/mentors'
    | '/notifications'
    | '/opportunities'
    | '/parent'
    | '/predictions'
    | '/profile'
    | '/resume'
    | '/schemes'
    | '/scholarships'
    | '/settings'
    | '/success-navigator'
    | '/success-stories'
    | '/voice'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/_app/admin'
    | '/_app/ai-mentor'
    | '/_app/analytics'
    | '/_app/applications'
    | '/_app/career-gps'
    | '/_app/community'
    | '/_app/dashboard'
    | '/_app/digital-twin'
    | '/_app/interventions'
    | '/_app/knowledge-graph'
    | '/_app/mentors'
    | '/_app/notifications'
    | '/_app/opportunities'
    | '/_app/parent'
    | '/_app/predictions'
    | '/_app/profile'
    | '/_app/resume'
    | '/_app/schemes'
    | '/_app/scholarships'
    | '/_app/settings'
    | '/_app/success-navigator'
    | '/_app/success-stories'
    | '/_app/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/voice': {
      id: '/_app/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/success-stories': {
      id: '/_app/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof AppSuccessStoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/success-navigator': {
      id: '/_app/success-navigator'
      path: '/success-navigator'
      fullPath: '/success-navigator'
      preLoaderRoute: typeof AppSuccessNavigatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scholarships': {
      id: '/_app/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof AppScholarshipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schemes': {
      id: '/_app/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AppSchemesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resume': {
      id: '/_app/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/predictions': {
      id: '/_app/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof AppPredictionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent': {
      id: '/_app/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AppParentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mentors': {
      id: '/_app/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof AppMentorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-graph': {
      id: '/_app/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/knowledge-graph'
      preLoaderRoute: typeof AppKnowledgeGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interventions': {
      id: '/_app/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof AppInterventionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/digital-twin': {
      id: '/_app/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof AppDigitalTwinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/career-gps': {
      id: '/_app/career-gps'
      path: '/career-gps'
      fullPath: '/career-gps'
      preLoaderRoute: typeof AppCareerGpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-mentor': {
      id: '/_app/ai-mentor'
      path: '/ai-mentor'
      fullPath: '/ai-mentor'
      preLoaderRoute: typeof AppAiMentorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiMentorRoute: typeof AppAiMentorRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppCareerGpsRoute: typeof AppCareerGpsRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDigitalTwinRoute: typeof AppDigitalTwinRoute
  AppInterventionsRoute: typeof AppInterventionsRoute
  AppKnowledgeGraphRoute: typeof AppKnowledgeGraphRoute
  AppMentorsRoute: typeof AppMentorsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppParentRoute: typeof AppParentRoute
  AppPredictionsRoute: typeof AppPredictionsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResumeRoute: typeof AppResumeRoute
  AppSchemesRoute: typeof AppSchemesRoute
  AppScholarshipsRoute: typeof AppScholarshipsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuccessNavigatorRoute: typeof AppSuccessNavigatorRoute
  AppSuccessStoriesRoute: typeof AppSuccessStoriesRoute
  AppVoiceRoute: typeof AppVoiceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiMentorRoute: AppAiMentorRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApplicationsRoute: AppApplicationsRoute,
  AppCareerGpsRoute: AppCareerGpsRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDigitalTwinRoute: AppDigitalTwinRoute,
  AppInterventionsRoute: AppInterventionsRoute,
  AppKnowledgeGraphRoute: AppKnowledgeGraphRoute,
  AppMentorsRoute: AppMentorsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppParentRoute: AppParentRoute,
  AppPredictionsRoute: AppPredictionsRoute,
  AppProfileRoute: AppProfileRoute,
  AppResumeRoute: AppResumeRoute,
  AppSchemesRoute: AppSchemesRoute,
  AppScholarshipsRoute: AppScholarshipsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuccessNavigatorRoute: AppSuccessNavigatorRoute,
  AppSuccessStoriesRoute: AppSuccessStoriesRoute,
  AppVoiceRoute: AppVoiceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
